export const LOWER_SUBMIT = "submit"
export const LOWER_FILLED = "filled"
export const LOWER_OUTLINED = "outlined"
export const LOWER_SMALL = "small"
export const LOWER_LARGE = "large"
export const LOWER_MIDDLE = "middle"
export const LOWER_NUMBER = "number";
export const HASH_LINK = "#";
export const COLON  = ": "
export const LOWER_TARGET_BLANK = "_blank";
export const COLOR_BLACK = "#000";
export const LOWER_COLOR_WHITE = "#fff";
export const LOWER_CENTER = "center";
export const LOWER_BODY_ONE = "body1";
export const LOWER_BASIC = "basic";
export const INITIAL_VALUES = { remember: true };
export const LOWER_OFF = "off";
export const LOWER_EMAIL = "email";
export const CAMEL_ON_BLUR = "onBlur";
export const LOWER_LABLE_BETWEEN_MIN_MAX =
  "${label} must be between ${min} and ${max}";
export const CAP_USER_NAME = "Username";
export const LOWER_USER_NAME = "username";
export const CAMEL_USER_ID = "userId";
export const UPPER_ID = "ID";
export const LOWER_TEXT_AREA = "textarea";
export const LOWER_DARK = "dark";
export const LOWER_LIGHT = "light";
export const LOWER_TRANSPARENT = "transparent";
export const LOWER_PASSWORD = "password";
export const CAP_REFERENCE = "Reference";
export const CAP_USER_CURRENCY = "User Currency"
export const LOWER_REFERENCE = "reference";
export const CAP_NOTES = "Notes";
export const CAP_PASSWORD = "Password";
export const LOWER_TEXT = "text";
export const LOWER_HORIZONTAL = "horizontal";
export const LOWER_VERTICAL = "vertical";
export const LOWER_CHECKED = "checked";
export const CAMEL_USER_NAME = "userName";
export const LOWER_ROLE = "role";
export const CAP_SEARCH = "Search";
export const CAP_LARGE = "Large";
export const CAP_SMALL = "Small";
export const CAP_CREDIT = "Credit";
export const LOWER_CREDIT = "credit";
export const CAP_CLIENT_PL = "Client P/L";
export const CAMEL_CLIENT_PL = "clientPL";
export const CAP_EXPOSURE = "Exposure";
export const LOWER_EXPOSURE = "exposure";
export const LOWER_ONE_O_BET_DOT_COM = "1obet.com"
export const CAP_EDIT = "Edit";
export const CAP_MAX_BET_SIZES = "Max Bet Sizes";
export const CAP_CHANGE_MAX_BET_SIZES = "Change Max Bet Sizes";
export const LOWER_EDIT = "edit";
export const CAP_UPDATE = "Update";
export const CAP_RECHARED_BY = "Recharged By";
export const CAP_RECHARES = "Recharges";
export const CAMEL_RECHARGED_BY = "rechargedBy";
export const CAMEL_CREATED_BY = "createdBy";
export const LOWER_AMOUNT = "amount";
export const CAP_AMOUNT = "Amount";
export const CAP_CREATED_BY = "Created By";
export const CAP_OPTIONS = "Options";
export const LOWER_OPTIONS = "options";
export const CAP_ACTION = "Action";
export const LOWER_ACTION = "action";